============================= test session starts ==============================

platform darwin -- Python 3.9.13, pytest-7.1.2, pluggy-1.0.0
rootdir: /Users/via/PycharmProjects/testTask
collected 18 items

tests/test_automat.py ................xx                                 [100%]


==================================== PASSES ====================================

=========================== short test summary info ============================

PASSED tests/test_automat.py::TestAutomat::test_positive_automat_1[0]

PASSED tests/test_automat.py::TestAutomat::test_positive_automat_1[1]

PASSED tests/test_automat.py::TestAutomat::test_positive_automat_1[99]

PASSED tests/test_automat.py::TestAutomat::test_positive_automat_1[100]

PASSED tests/test_automat.py::TestAutomat::test_positive_automat_3[101]

PASSED tests/test_automat.py::TestAutomat::test_positive_automat_3[102]

PASSED tests/test_automat.py::TestAutomat::test_positive_automat_3[200]

PASSED tests/test_automat.py::TestAutomat::test_positive_automat_5[201]

PASSED tests/test_automat.py::TestAutomat::test_positive_automat_5[202]

PASSED tests/test_automat.py::TestAutomat::test_positive_automat_5[500]

PASSED tests/test_automat.py::TestAutomat::test_positive_automat_10[501]

PASSED tests/test_automat.py::TestAutomat::test_positive_automat_10[502]

PASSED tests/test_automat.py::TestAutomat::test_positive_automat_10[700]

PASSED tests/test_automat.py::TestAutomat::test_neg_automat_exception[700]

PASSED tests/test_automat.py::TestAutomat::test_neg_automat_exception[None]

PASSED tests/test_automat.py::TestAutomat::test_neg_automat_exception[]

XFAIL tests/test_automat.py::TestAutomat::test_neg_automat_fall[-1]

XFAIL tests/test_automat.py::TestAutomat::test_neg_automat_fall[-100]

======================== 16 passed, 2 xfailed in 0.06s =========================



#### Запуск -  python -m pytest -rA >TaskTestData.md
